version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:24.0.6-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:24.0.6-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis


  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  collab:
    image: collabora/code
    restart: always
    networks:
      - proxy-tier
    depends_on:
      - proxy
      - letsencrypt-companion
    cap_add:
      - MKNOD
    ports:
      - 9980:9980
    environment:
      - aliasgroup1=https://cloud.DOMAIN.TDL:443
      - username=admin
      - password=CREATE-A-SECURE-PASSWORD-HERE
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=9980
      - VIRTUAL_HOST=office.DOMAIN.TLD
      - LETSENCRYPT_HOST=office.DOMAIN.TLD
      - LETSENCRYPT_EMAIL=YOUR-EMAIL@DOMAIN.TDL


volumes:
  db:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:
